### ISSUE TITLE
最近一次commit移除了fake-ip-filter

### ISSUE THREAD

**Issue by TeaWu** [yyhhyyyyyy/selfproxy#1]
请问一下最近一次commit移除了fake-ip-filter，这个不需要加入了吗？

**Comment by yyhhyyyyyy** [comment]
![image](https://github.com/user-attachments/assets/797b6d7c-c3a8-4869-8278-fc688570af07)

请看readme

**Comment by TeaWu** [comment]
> ![image](https://private-user-images.githubusercontent.com/95077259/365003504-797b6d7c-c3a8-4869-8278-fc688570af07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTAxNjAsIm5iZiI6MTcyNTU4OTg2MCwicGF0aCI6Ii85NTA3NzI1OS8zNjUwMDM1MDQtNzk3YjZkN2MtYzNhOC00ODY5LTgyNzgtZmM2ODg1NzBhZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAyMzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDczMzUwMjhjODRhMzA0OWM0OWYwZWJkNWJkNzYzNmI4NmQ4ZDIzM2JjNjJjMTVmN2IzMDU0NTJmZWQwODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D-87E1bzVRNoQLBJrBXmHOaUZM_SxhQXDVSZ-X7wKDo)
> 
> 请看readme

嗯嗯，今天注意到这一部分了，所以主动关了issue，哈哈，感谢回复，目前正在搞手机端的mihomo配置
