### ISSUE TITLE
Mihomo_Party Profile Check Failed…

### ISSUE THREAD

**Issue by cy-i** [yyhhyyyyyy/selfproxy#3]
1、如果是节点，不是订阅，就会报错。
![0001](https://github.com/user-attachments/assets/d7eb7533-83fe-47a4-b2e9-e21fcda2afd1)
加入：proxies: allProxies.length > 0 ? allProxies : ["DIRECT"],后正常

2、如果使用的是订阅，但是订阅里的国家，没有规则中的国家，也会报错，报错内容如上，都是手动选择部分报错！
`        {
            name: "手动选择",
            type: "select",
            icon: "https://raw.githubusercontent.com/Orz-3/mini/master/Color/Cylink.png",
            proxies: ["HK - 手动选择", "TW - 手动选择", "SG - 手动选择", "JP - 手动选择", "US - 手动选择", "DE - 手动选择", "KR - 手动选择", "UK - 手动选择", "CA - 手动选择", "AU - 手动选择", "FR - 手动选择", "IN - 手动选择", "BR - 手动选择", "SE - 手动选择"],
	 },`
要在这里删除订阅里没有的国家，就正常。

**Comment by yyhhyyyyyy** [comment]
已经在 上一个 commit 修复了
![image](https://github.com/user-attachments/assets/6217ae39-9d88-4bed-b9e4-5c327260749b)
