### ISSUE TITLE
关于yaml文件中DNS规则导致chrome谷歌翻译插件无法代理

### ISSUE THREAD

**Issue by AKAGItietie** [yyhhyyyyyy/selfproxy#4]
大佬您好，抱歉打扰您了。想问下覆写规则之后，如不打开mihomo”接管DNS设置选项“失效yaml文件中dns设置，将导致chrome/edge谷歌网页翻译插件，第三方翻译插件等无法走代理进行翻译。使用[SwitchyOmega]强制全网页走代理也会发生翻译失败网络连接错误的提示。(*.translate.googleapis.com）
直接访问网页版谷歌翻译没有问题。

**Comment by yyhhyyyyyy** [comment]
1. `接管DNS设置选项` 一定要关闭的  不然覆写的 DNS 部分将不会生效
2. 尝试注释覆写脚本的main函数部分的     overwriteNameserverPolicy   overwriteHosts 
```js
function main (params) {
    if (!params.proxies) return params;
    overwriteRules (params);
    overwriteProxyGroups (params);
    overwriteDns (params);
    overwriteBasicOptions (params);
    overwriteFakeIpFilter (params);
    overwriteTunnel (params);
    // overwriteNameserverPolicy (params);
    // overwriteHosts (params);
    return params;
}
```
再试试看 可否正常翻译  
按你提供的域名 应该是不会走如这部分的才对  还是排除下干扰项吧
3. 把这个域名写个走代理的规则 放到 `customRules`中试试

**Comment by AKAGItietie** [comment]
好的，感谢您，我尝试一下
